export const quotes = [
  "Life is a bit like the weather; it can be unpredictable, but it's always beautiful in its own way.",
  "Just as the weather can change, so can life. Embrace the storms and cherish the sunshine.",
  "In the midst of life's storms, find shelter in the beauty of nature's elements, like the rain's gentle embrace.",
  "The weather reminds us that change is the only constant in life. Embrace it with an open heart.",
  "Life, like the weather, is a mix of sunshine and rain. Both are necessary for growth.",
  "When life gives you rain, look for rainbows. When it gives you sun, soak in the warmth of the moment.",
  "The weather mirrors the complexity of human emotions, from the stormy days to the calm afternoons.",
  "Find meaning in the ever-changing sky of life, where every cloud has a silver lining.",
  "Just as the weather affects the world, our actions ripple through life's ecosystem. Choose to make a positive impact.",
  "Life is a journey, and the weather is a part of that journey. Embrace every forecast with gratitude and resilience.",
  "The changing weather reminds us that life's challenges are temporary, and brighter days are on the horizon.",
  "In the symphony of life, weather is the ever-changing melody that keeps us in tune with the universe.",
  "Life is like the seasons, constantly changing. Embrace each season with open arms, for they all have their unique beauty.",
  "The weather paints the canvas of our lives, with each day offering a new brushstroke of experiences.",
  "Just as weather patterns shift, our lives ebb and flow. Adaptation is the key to thriving in any climate.",
  "Life's journey is a weathered path, filled with sunshine and storms. Both contribute to our growth and character.",
  "The weather teaches us patience, for even the darkest clouds eventually give way to the sun's warm embrace.",
  "Nature's elements are a reflection of life's diversity. Embrace each moment as a unique and precious gift.",
  "The weather holds the secrets of the world, just as life holds the mysteries of the heart.",
  "Life, like the weather, is a delicate balance between chaos and serenity. Find your equilibrium in the midst of it all.",
  "Life's journey is like a long road trip with changing weather. Keep your spirits high and enjoy the ride.",
  "Just as the weather transitions, so does life. Embrace the transitions, for they are the essence of growth.",
  "Weather is the poetry of the skies, just as life is the poetry of the heart. Both are ever-changing and beautiful.",
  "Life is a collection of moments, just like the weather is a collection of elements. Cherish each one.",
  "In the grand story of life, the weather serves as a backdrop to our adventures, making each moment unique.",
  "The weather reminds us of the power of transformation. Change is inevitable, but it can lead to beautiful outcomes.",
  "Nature's elements are a reminder that life's beauty lies in its diversity. Embrace the differences around you.",
  "The weather may be unpredictable, but the beauty of life lies in its surprises and unexpected moments.",
  "Life's journey is a mosaic of experiences, with the weather adding its own vibrant colors to the tapestry.",
  "The weather, like life, is a mix of sunshine and rain. Both are essential for the growth of the soul.",
];
